### ISSUE TITLE
black list for deleted items like users, stalls and products

### ISSUE THREAD

**Issue by plebomoto** [PlebeianTech/plebeian.market#356]
Things that are deleted get written right back into db when encountered in the wild by clients

**Comment by gzuuus** [comment]
Great! I was thinking in this already. Would love to hear your ideas to implement this. I think the most straight forward solution may be flag blacklisted users in the db instead of remove them

**Comment by plebomoto** [comment]
> I think the most straight forward solution may be flag blacklisted users in the db instead of remove them

makes sense!
