### ISSUE TITLE
The nostr DM's unreadable

### ISSUE THREAD

**Issue by ChiefmonkeyArt** [PlebeianTech/plebeian.market#372]
The nostr DM of a purchase is unformatted... needs MD 

<img width="1259" alt="nostr-DM-unformatted-code" src="https://github.com/user-attachments/assets/1c0a0c8b-78cc-477d-81e5-022f7f3996c2">

**Comment by gzuuus** [comment]
This is how nip15 specifies the different interaction between users: https://github.com/nostr-protocol/nips/blob/master/15.md#step-1-customer-order-event
Closing this issue for now, since we cannot do nothing until the spec is updated (WIP)
