### ISSUE TITLE
[Mobile] Tapping on image triggers add to cart

### ISSUE THREAD

**Issue by Czino** [PlebeianTech/plebeian.market#382]
When tapping on a product image on a product listing page where the Add to cart button would appear, the add to cart button is triggered as well, which I didn't expect.

Expected behavior would be that only the add to cart button appears at first. But I'd suggest to always show Add to Cart for devices with touchscreens.

https://github.com/user-attachments/assets/6512ed68-a61b-444c-82e8-2ce418ef4c2e

**Comment by plebomoto** [comment]
@Aslemammad @gzuuus different layout on mobile or take the buttons out of the image all together? button just can't be in image on mobile.
