### ISSUE TITLE
Unable to update user data

### ISSUE THREAD

**Issue by Czino** [PlebeianTech/plebeian.market#384]
When navigating to [Profile Settings](https://staging.plebeian.market/settings/account/profile), I am unable to update any data.

Opening the console I find following error message:

```
34.DSkXmXyq.js:1 TypeError: V.sign is not a function
    at HTMLFormElement._e (34.DSkXmXyq.js:1:10514)
```

**Comment by gzuuus** [comment]
Cannot reproduce this, can you provide more details about this error? what browser were you using? you were using a nip07 extension? what os are you using?

**Comment by Czino** [comment]
Cannot reproduce this bug anymore either, all good then 👍
