### ISSUE TITLE
Make header image icon easier to see

### ISSUE THREAD

**Issue by ChiefmonkeyArt** [PlebeianTech/plebeian.market#387]
Noticed by Isolabell in tg 
![image](https://github.com/user-attachments/assets/bdfc9c06-81cf-40ae-8a66-2f497a127ea7)

**Comment by isolabellart** [comment]
This is fixed already 👌
<img width="690" alt="Screenshot 2024-11-14 alle 12 51 33" src="https://github.com/user-attachments/assets/dbdfdfb1-213b-446a-9a58-c48b88d6a5a1">
