### ISSUE TITLE
New Product - Currency/Price 

### ISSUE THREAD

**Issue by bitcoinbekka** [PlebeianTech/plebeian.market#423]
When I add a new product to the stall and set the price in sats/btc will I have to go in as the stall owner and change the price of my products every time the bitcoin prices changes? or vice versa, if I list my product in dollars but it is displayed in sats on the site, and the price changes does the stall owner need to go in and update the price to reflect the proper exchange rate? 

- For example, the yellow plushies are $100 USD, which was about million sats but when the btc price goes up, the sats amount will be less than million… is it the stall owner responsibility to change the price of the product?

that seems like a lot of work for a user to keep up-to-date with the exchange rates and updating their products every time...

**Comment by yojimble** [comment]
Yes if you use sats you would have to keep an eye on prices, the fiat currency option is doing this automagically for me - connected to an exchange rate in the background?

**Comment by gzuuus** [comment]
If you set the currency in your stall to sats or btc there are no more conversions to do. If you set the currency in any fiat unit, it will use the yadio api to get the current exchange rate. This rate is updated every 5 minutes.
