### ISSUE TITLE
Homepage Layout

### ISSUE THREAD

**Issue by bitcoinbekka** [PlebeianTech/plebeian.market#427]
I didn’t notice right away that there where products shown on the homepage…as the category section takes up the entire upper section on the homepage	… I just didn’t scroll down but it would be nice to see some products at the top… it is prime real estate on the homepage. 

It would be nice to have a "featured" products banner on the top portion of the homepage so it looks like a marketplace instead of just a list of categories right  at the top 
![Testing notes 3](https://github.com/user-attachments/assets/f12e84e9-ef65-4279-85e3-6809806dc2a2)

**Comment by gzuuus** [comment]
When there are feature products, there are already placed at the top of the page 👌
