### ISSUE TITLE
PWA Upload Image Button is unresponsive

### ISSUE THREAD

**Issue by ChiefmonkeyArt** [PlebeianTech/plebeian.market#449]
In the "Edit Stall" page and "Edit Product" page the Upload Image Button is unresponsive 

Click it an nothing happens 

<img width="954" alt="Screenshot 2024-11-27 at 16 47 08" src="https://github.com/user-attachments/assets/682bd523-c555-491b-9572-ebc93e1e3503">

**Comment by gzuuus** [comment]
Mmm no significant changes on this lately, are you sure? i just tested and worked. Can you test again?

**Comment by ChiefmonkeyArt** [comment]
Yeah... I just loaded it up again and did the Reload... seems to be working no problems... thank you
